apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project2-api
  namespace: p2
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: project2.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project2-api
                port:
                  number: 80
