apiVersion: v1
kind: Service
metadata:
  name: {{ include "project2-api.fullname" . }}
  labels:
    app: {{ include "project2-api.name" . }}
spec:
  selector:
    app: {{ include "project2-api.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
